Spaikaven/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('login.urls')),
    url(r'^signup$',include('signup.urls')),
    url(r'^home/', include('home.urls')),
    
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
        url(r'^$', views.home_view, name='home'),
        url(r'^compose$', views.compose_view, name='compose'),
]

login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'

urlpatterns = [
	url(r'^$', views.login_view, name='login'),
        url(r'^logout$', views.logout_view, name='logout'),
     
]

signup/urls.py
from django.conf.urls import url
from . import views

app_name = 'signup'

urlpatterns = [
	url(r'^$', views.signup_view, name='signup'),
     
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Message(models.Model):
    message = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(User, default=None, on_delete=models.CASCADE,)

    def __str__(self):
        return self.message

login/models.py
from django.db import models

# Create your models here.

signup/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from . import models

class CreateMessage(forms.ModelForm):
    class Meta:
        model = models.Message
        fields = ['message']

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import forms
from .models import Message


# Create your views here.
@login_required(login_url='login:login')
def home_view(request):
    message = Message.objects.all().order_by('-date')
    return render (request, 'home/home.html', {'messages': message})

@login_required(login_url='login:login')
def compose_view(request):
    if request.method =='POST':
        form = forms.CreateMessage(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.sender = request.user
            instance.save()
            return redirect('home:home')
    else:
        form = forms.CreateMessage()
    return render (request, 'home/compose.html', {'form': form})



login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def login_view(request):
    if request.method == 'POST':
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()    # user()-> variable
            login(request, user)
            if'next'in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home:home')
    else:
        login_form = AuthenticationForm()
    return render(request, 'login/login.html', {'form': login_form})

def logout_view(required):
    logout(required)
    return redirect('login:login')

signup/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        signup_form = UserCreationForm(request.POST)
        if signup_form.is_valid():
            signup_form.save()
            return redirect('login:login')
    else:
        signup_form = UserCreationForm()
    return render(request, 'signup/signup.html', { 'form': signup_form})

home/templates/home/compose.html
{% extends "main.html" %}

{% block title %}Compose{% endblock %}

{% block body %}
<div class="container custom_body">
    <div class="row head">
      <section class="col-lg-12">
          <div class="col-lg-6">
            <h1>Soviet resistance network</h1>
          </div>
          <div class="col-lg-3">
              <h1><a href="{% url 'home:home' %}"><button type="button" class="btn btn-lg btn-default btn-block">Home</button></a></h1>
          </div>
          <div class="col-lg-3">
              <form action="{% url 'login:logout' %}" method="post">
                  {% csrf_token %}
                  <h1><button type="submit" class="btn btn-lg btn-default btn-block">Logout</button></h1>
              </form>
          </div>
      </section>
    </div>
    <div class="row ">
      <section class="col-lg-12">
          <form action="{% url 'home:compose' %}" method="post">
              {% csrf_token %}
              {{ form }}
              <br />
              <input type="submit" value="Send" class="btn pull-right btn-default" style="margin-right:28.5%">
          </form>
      </section>
    </div>
</div>
{% endblock %}

home/templates/home/home.html
{% extends "main.html" %}

{% block title %}Home{% endblock %}

{% block body %}

<div class="container custom_body">
    <div class="row head">
      <section class="col-lg-12">
          <div class="col-lg-6">
            <h1 style = "margin-left:-0.9em;">Soviet resistance network</h1>
          </div>
          <div class="col-lg-3">
              <h1><a href="{% url 'home:compose' %}"><button type="button" class="btn btn-lg btn-default btn-block">Send Message</button></a></h1>
          </div>
          <div class="col-lg-3">
              <form action="{% url 'login:logout' %}" method="post">
                  {% csrf_token %}
                  <h1><button type="submit" class="btn btn-lg btn-default btn-block" style="margin-left:1.5em;">Logout</button></h1>
              </form>
          </div>
      </section>
    </div>
    <div class="row msg_body">
      <section class="col-lg-12">
          {% for msg in messages %}
            <div class="row custom_row">
                <section class="col-lg-12">
                    <div class="row" style="margin-bottom:1em;">
                        <div class="col-lg-8 sender">
                            {{ msg.sender }}
                        </div>
                        <div class="col-lg-4 date">
                            {{ msg.date }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 msg">
                        <p>
                            {{ msg.message }}
                        </p>
                        </div>
                    </div>
                </section>


            </div>
          {% endfor %}
      </section>
    </div>
</div>
{% endblock %}

login/templates/login/login.html
{% extends "main.html" %}

{% block title %}Login{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
        <form class="form-group" action="{% url 'login:login' %}" method="post">
          <div style="margin: 1em auto 1em auto; text-align: center;max-width: 75%;">
            <h2>Soviet resistance network</h2>
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
            <input type="text" name="next" value="{{ request.GET.next }}">
            {% endif %}

          </div>
          <input type="submit" value="Login" class="btn btn-default" style="min-width:80px;">
          <a role="button" href="{% url 'signup:signup' %}"><button type="button" style="margin-top:1em;min-width:80px;" class="btn center-block btn-default">Sign Up</button></a>
        </form>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

login/templates/main.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width , initial-scale = 1" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}" />
        <link rel="stylesheet" href="{% static '/css/mystyles.css' %}" />
    </head>
    <body>
    {% block body %}
    {% endblock %}
    </body>
    <script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/bootstrap.js' %}" ></script>
</html>


signup/templates/signup/signup.html
{% extends 'main.html' %}

{% block title %}Signup{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
        <form class="form-group" action="{% url 'signup:signup' %}" method="post">
          <div style="margin: 1em auto 1em auto; text-align: center;max-width: 75%;">
            <h2>Soviet resistance network</h2>
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
            <input type="text" name="next" value="{{ request.GET.next }}">
            {% endif %}

          </div>
          <input type="submit" value="Sign Up" class="btn btn-default" style="min-width:80px;">
          <a role="button" href="{% url 'login:login' %}"><button type="button" style="margin-top:1em;min-width:80px;" class="btn center-block btn-default">Back to Login</button></a>
        </form>
    </div>
  </div>
</div>
{% endblock %}
</form>